apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-test-app
  namespace: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-test-app
  template:
    metadata:
      labels:
        app: nodejs-test-app
    spec:
      containers:
        - name: nodejs-test-app
          image: ${DOCKER_IMAGE}:${DOCKER_TAG}
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-test-app
  namespace: test-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: nodejs-test-app
